name: Generate HTML

on:
  repository_dispatch:
  workflow_dispatch:
  push:

env:
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'true'

    - name: Install Hexo and theme
      env:
        DEBIAN_FRONTEND: noninteractive
      run: modify/env.sh

    - name: neofetch
      run: neofetch --off

    - name: Build
      run: |
        hexo generate
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload to artifact
      uses: actions/upload-artifact@main
      with:
        name: build-${{ env.FILE_DATE }}.zip
        path: public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2.0.3
      with:
        retain_days: 1
        keep_minimum_runs: 5
